config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
    resources :items
  end

  root 'workouts#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :workout
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @workout = Workout.find(params[:workout_id])
    @item = @workout.items.build(item_params)

    if @item.save
      redirect_to workout_path(@workout), notice: "新增項目成功"
    else
      render :new
    end
  end

  def edit
    @workout = Workout.find(params[:workout_id])
    @item = @workout.items.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:workout_id])
    @item = @workout.items.find(params[:id])

    if @item.update(item_params)
      redirect_to workout_path(@workout), alert: "修改項目成功"
    else
      render :edit
    end
  end

  def destroy
    @workout = Workout.find(params[:workout_id])
    @item = @workout.items.find(params[:id])
    @item.destroy
    redirect_to workout_path(@workout), alert: "刪除項目成功"
  end

  private

  def item_params
    params.require(:item).permit(:name, :set, :rep_time)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    @workouts = Workout.all
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      redirect_to workouts_path, notice: "新增紀錄成功！"
    else
      render :new
    end
  end

  def show
    @workout = Workout.find(params[:id])
    @items = @workout.items
  end

  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])

    if @workout.update(workout_params)
      redirect_to workout_path(@workout), alert: "更新記錄成功！"
    else
      render :edit
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy
    redirect_to workouts_path, alert: "刪除紀錄成功！"
  end


  private

  def workout_params
    params.require(:workout).permit(:goal, :feeling, :total_time, :workout_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger}
    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true}
    close_button = content_tag(:button, "x", close_button_options)

    alerts = flash.map do |type, message|
      alert_message = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_message, class: alert_class)
    end
    alerts.join("\n").html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/common/_footer.html.haml
%footer.container{:style => "margin-top: 100px;"}
  %p.text-center Build by Rorusage

app/views/common/_navbar.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{:type => "button", "data-toggle" => "collapse", "data-target" => "#example-navbar-collapse"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Workout Log

    .collapse.navbar-collapse{:id => "example-navbar-collapse"}
      %ul.nav.navbar-nav.navbar-right
        %li= link_to("New Workout Log", new_workout_path)

app/views/items/_item.html.haml
.col-md-12
  = simple_form_for [@workout, @workout.items.build] do |f|
    .form-group
      = f.input :name, input_html: { class: "form-control" }
      = f.input :set, input_html: { class: "form-control" }
      = f.input :rep_time, input_html: { class: "form-control" }
    = f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."}

app/views/items/_new.html.haml
.col-md-12
  = simple_form_for [@workout, @workout.items.build] do |f|
    .form-group
      = f.input :name, input_html: { class: "form-control" }
      = f.input :set, input_html: { class: "form-control" }
      = f.input :rep_time, input_html: { class: "form-control" }
    = f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."}

app/views/items/edit.html.haml
.cl-md-12
  %h3 修改項目
  %br

  = simple_form_for [@workout, @item] do |f|
    .form-group
      = f.input :name, input_html: { class: "form-control" }
      = f.input :set, input_html: { class: "form-control" }
      = f.input :rep_time, input_html: { class: "form-control" }
    = f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutLog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= render "common/navbar" %>
  <%= notice_message %>
  <%= yield %>
</div>
<%= render "common/footer" %>

</body>
</html>

app/views/workouts/_item_fields.html.haml
.nested-fields
  = f.input :name, input_html: { class: "form-control" }
  = f.input :set, input_html: { class: "form-control" }
  = f.input :rep_time, input_html: { class: "form-control" }
  = link_to_remove_association "Remove Item", f

app/views/workouts/edit.html.haml
.col-md-4.col-md-offset-4
  %h1 修改健身紀錄
  %br

  =simple_form_for @workout do |f|
    .form-group
      = f.input :workout_date
      = f.input :goal, input_html: { class: "form-control" }
      = f.input :feeling, input_html: { class: "form-control" }
      = f.input :total_time, input_html: { class: "form-control" }
    = f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."}

app/views/workouts/index.html.haml
.col-md-4.col-md-offset-4
  - @workouts.each do |workout|
    %h3= workout.workout_date.strftime("%A %B %d")
    %h3= link_to(workout.goal, workout_path(workout))

    .button-group
      = link_to("Edit", edit_workout_path(workout), class: "btn btn-primary")
      = link_to("Delete", workout_path(workout), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"})
    %hr

app/views/workouts/new.html.haml
.col-md-4.col-md-offset-4
  %h1 新增健身紀錄
  %br

  =simple_form_for @workout do |f|
    .form-group
      = f.input :workout_date
      = f.input :goal, input_html: { class: "form-control" }
      = f.input :feeling, input_html: { class: "form-control" }
      = f.input :total_time, input_html: { class: "form-control" }
    = f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."}

app/views/workouts/show.html.haml
.col-md-4.col-md-offset-4
  %h3 Goal : #{@workout.goal}
  %h5= @workout.workout_date.strftime("%A %B %d")
  %h4 Feeling : #{@workout.feeling}
  %h4 Total Time : #{@workout.total_time}
  = link_to("Back", workouts_path, class: "btn btn-info")
  = link_to("Edit", edit_workout_path(@workout), class: "btn btn-primary")
  = link_to("Delete", workout_path(@workout), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"})
  %hr

  %h3 Items :
  %br

  - @items.each do |item|
    %h4 Do what : #{item.name}
    %h4 Set : #{item.set}
    %h4 Rep. : #{item.rep_time}

    .button_group
      = link_to("Edit", edit_workout_item_path(@workout, item), class: "btn btn-primary")
      = link_to("Delete", workout_item_path(@workout, item), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"})
    %hr
  = render "items/new"